---

# its recommended to connect ansible to localhost which has kubectl installed which has remote access to k8s server 
- hosts: all
  connection: local
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  tasks:
    - import_role:
        name:       kubernetes_db_replication
        tasks_from: deploy